name: CI

on:
  pull_request:

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Install Requirements
        run: pip install -r requirements_dev.txt

      - name: Run linter
        run: flake8 seshypy/ tests/

  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    needs: lint
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Install Requirements
        run: |
          pip install -r requirements_dev.txt
          pip install tox

      - name: Run tests
        run: tox

  version-changes:
    name: Check VERSION changes (new version)
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    outputs:
      version_changes: ${{ steps.filter.outputs.version }}
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Filter paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
            filters: |
              version:
                - 'VERSION'
      - name: Version changed
        if: steps.filter.outputs.version == 'true'
        run: echo "Version changed, need to republish distributions"

      - name: Version didn't change
        if: steps.filter.outputs.version != 'true'
        run: echo "Version didn't change, no distribution publishing"

  build-and-publish:
    name: TestPyPI - Build and publish Python distributions
    runs-on: ubuntu-latest
    needs: [pytest, version-changes]
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        # # check if we need to distribute
        if: |
          needs.version-changes.outputs.version_changes == 'true'
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/

